# Generated by Django 4.2.1 on 2023-05-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('datetime_checkin', models.DateTimeField(auto_now_add=True)),
                ('datetime_checkout', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
