# Generated by Django 4.1.5 on 2023-05-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visiting_staff',
            field=models.CharField(default='Ali', max_length=100),
            preserve_default=False,
        ),
    ]
